import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '../components/header';
import Footer from '../components/Footer';

import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang='en'>
//       <body className={inter.className}>
//         <ClerkProvider>
//           <Header />
//           {children}
//           <Footer/>
//         </ClerkProvider>
//       </body>
//     </html>
//   );
// }


// import { Metadata } from "next";
import "../../styles/globals.css";

let title = "Dream Room Generator";
let description = "Generate your dream room in seconds.";
let ogimage = "https://roomgpt-demo.vercel.app/og-image.png";
let sitename = "roomGPT.io";

export const metadata: Metadata = {
  title,
  description,
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    images: [ogimage],
    title,
    description,
    url: "https://roomgpt-demo.vercel.app",
    siteName: sitename,
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    images: [ogimage],
    title,
    description,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
 
      <body className="bg-light text-black">
        <ClerkProvider>
        <Header/> 
        {children}
        <Analytics />

        <Footer/>
        </ClerkProvider>
        
      </body>
    </html>
  );
}
